export const mockUserProfileCard = {
  image: 'https://github.com/shadcn.png',
  fullname: 'John Doe',
  username: 'JohnDoe',
  profileDescription: 'Frontend developer. Coffee lover ☕. Sharing tips on React and TypeScript.',
  posts: 128,
  followers: 2400,
  following: 530,
  isOnline: true,
  status: 'busy' as const,
  joinDate: 'March 2021',
  location: 'San Francisco, CA',
  website: 'https://johndoe.dev',
  badges: ['Frontend', 'TypeScript', 'React'],
  size: 'md' as const,
};

export const mockUserPosts = [
  {
    image: 'https://github.com/shadcn.png',
    fullname: 'John Doe',
    username: 'JohnDoe',
    postContent: `☕ Morning tip: Use \`useMemo\` only when you notice performance issues. Premature optimization can hurt readability. #react #typescript`,
    postTimestamp: '1h ago',
    postImage: '',
  },
  {
    image: 'https://github.com/shadcn.png',
    fullname: 'John Doe',
    username: 'JohnDoe',
    postContent: `✨ Finally migrated my side project to TypeScript. Caught 3 bugs instantly. Worth every minute. #typescript #devlife`,
    postTimestamp: '4h ago',
    postImage: '',
  },
  {
    image: 'https://github.com/shadcn.png',
    fullname: 'John Doe',
    username: 'JohnDoe',
    postContent: `🚀 Just released a custom React hook for debounce logic. Cleaner, reusable, and tested! Open source coming soon.`,
    postTimestamp: '1d ago',
    postImage: 'https://user-images.githubusercontent.com/123456789/preview-debounce-hook.png',
  },
  {
    image: 'https://github.com/shadcn.png',
    fullname: 'John Doe',
    username: 'JohnDoe',
    postContent: `🤓 Refactored a legacy component with composition + Tailwind. Amazing how much cleaner it looks now.`,
    postTimestamp: '3d ago',
    postImage: 'https://images.unsplash.com/photo-1587620931232-919cedb76c68',
  },
  {
    image: 'https://github.com/shadcn.png',
    fullname: 'John Doe',
    username: 'JohnDoe',
    postContent: `📚 Reading "The Pragmatic Programmer" again. Every chapter hits different when you've been coding for a few years.`,
    postTimestamp: '6d ago',
    postImage: '',
  },
];
